### ISSUE TITLE
Server-side rendering issue with Angular Universal

### ISSUE THREAD

**Issue by Adrian-Ghita** [lentschi/ngx-ellipsis#34]
Angular version: 9.1.4 (Ivy enabled)

When running in SSR mode (on 2.2.2 version), an error is thrown (only on server-side render):
`TypeError: this.removeWindowResizeListener is not a function`

It worked fine on v2.1.2.

**Comment by squelix** [comment]
I have the same issue, it worked fine on `v2.2.1` but in `v2.2.2` it doesn't work :/

This is maybe this commit: https://github.com/lentschi/ngx-ellipsis/commit/96a3caf095c9631b716668823b5e9b481e05f6b3 ?

**Comment by lentschi** [comment]
> This is maybe this commit: 96a3caf ?

Yes - I merged https://github.com/lentschi/ngx-ellipsis/pull/31 and forgot to test SSR. Looking into it...

**Comment by lentschi** [comment]
@Adrian-Ghita @squelix Fixed in 2.2.3.

But heed my warning in #27 (Maybe I should copy this to the `README`... :thinking: ):

> Finally I would like to point out one other thing (You may already know this, but someone else stumbling across this ticket might wonder about it):

>One of the things Angular Universal was made for is to accelerate initial page display. (So you can see some content before the page becomes interactive.) So though version ngx-ellipsis 2.0.8 did fix some SSR initialization errors, it doesn't comply with the acceleration aspect at all: To calculate the letters that will fit inside the ellipsis element, the lib uses HTMLElement properties such as clientWidth and scrollWidth, which are unavailable on the server side (AFAIK Angular Universal *cannot* know how exactly text will be rendered on the OS and browser the client uses)
So in short: The ellipsis is not being being precalculated on the server and it will slow down the client. If anyone has an idea on how to prevent that, I'm all ears :wink:

**Comment by squelix** [comment]
It will slow down the client ok, but it does not matter because we want that Google Bot take the string, for example, full.
